coverage_service: cobertura_xml
xcodeproj: MobileChallengeLuizaLabs.xcodeproj
input_format: profdata
output_directory: Coverage/
build_directory: build/Build/
scheme: 'MobileChallengeLuizaLabs'
ignore:
