name: CI

on:
  pull_request:
    branches: [ main ]

jobs:

  build:

    name: Build Project
    runs-on: macos-latest

    steps:
    - name: Checkout repositor
      uses: actions/checkout@v2 
      with: 
        fetch-depth: 0

    - name: Set Gems
      run: |
        gem install bundler
        bundle install

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.4

    - name: Build app
      run: |
        set -o pipefail
        slather setup
        bundle exec pod install
        xcodebuild build-for-testing \
        -project 'MobileChallengeLuizaLabs.xcworkspace' \
        -scheme 'MobileChallengeLuizaLabs' \
        -destination 'platform=iOS Simulator,name=iPhone 8' \
        -derivedDataPath build \
        | xcpretty 

    - name: Archive derived data artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: build
  test:
    name: Test Project
    runs-on: macOS-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
    
    - name: Download derived data artifact
      uses: actions/download-artifact@v1
      with:
        name: build

    - name: Set Gems
      run: |
        gem install bundler
        bundle install

    - name: Set Xcode version
      uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12.4

    - name: Run tests
      run: |
        set -o pipefail
        xcodebuild test-without-building \
        -project 'MobileChallengeLuizaLabs.xcworkspace' \
        -scheme 'MobileChallengeLuizaLabs' \
        -destination 'platform=iOS Simulator,name=iPhone 8' \
        -derivedDataPath build \
        -enableCodeCoverage YES \
        | xcpretty
    
    - name: Coverage report
      run: slather coverage -x --binary-basename 'Bootcamp-Magic'
      
    - name: Post coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./Coverage/cobertura.xml
        fail_ci_if_error: true    
